In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
import pprint
from sklearn.preprocessing import StandardScaler
%matplotlib inline

from sklearn.metrics import f1_score, recall_score, accuracy_score, precision_score, confusion_matrix
from sklearn.metrics import r2_score, roc_auc_score, roc_curve, classification_report
import xgboost as xgb
from sklearn.model_selection import cross_validate
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import KFold

FULL_DATASET = 'FULL TRAINING SET updated.csv'

### Round of 64

In [2]:
DATASET1 = 'R64 TESTING SET.csv'
df = pd.read_csv(FULL_DATASET)
df1 = pd.read_csv(DATASET1)

print(df.head())
print(df1.head())

   Round  Seed1           Team1           Team2  Seed2  Result  K TEMPO  \
0      1      1  North Carolina  Mount St Marys     16       1   7.6847   
1      1      2       Tennessee        American     15       1  11.7930   
2      1      3      Louisville        Boise St     14       1  -5.4011   
3      1      4   Washington St        Winthrop     13       1  -4.4331   
4      1      5      Notre Dame    George Mason     12       1   8.4834   

   K TEMPO RANK  KADJ T  KADJ T RANK  ...  BADJT RANK  AVG HGT RANK  \
0          -120  6.6882         -134  ...        -150          -195   
1          -309  9.9867         -301  ...        -300          -167   
2           151 -5.5255          142  ...         141           -67   
3            44 -3.1859           38  ...          33          -200   
4          -260  7.9935         -263  ...        -250          -148   

   EFF HGT RANK  EXP RANK  TALENT RANK  FT% RANK  OP FT% RANK  PPPO RANK  \
0           -91       -49         -197      -1

In [3]:
df.isnull().sum()

Round             0
Seed1             0
Team1             0
Team2             0
Seed2             0
                 ..
FT% RANK          0
OP FT% RANK       0
PPPO RANK         0
PPPD RANK         0
ELITE SOS RANK    0
Length: 99, dtype: int64

In [4]:
# Drop player names
df = df.drop(['Team1', 'Team2', 'Round', 'Seed1', 'Seed2'], axis=1)
df1 = df1.drop(['Team1', 'Team2', 'Round', 'Seed1', 'Seed2'], axis=1)

In [5]:
# Split dataset into X and Y
X_train = df.iloc[:, df.columns != 'Result']
y_train = df['Result']
X_test = df1

In [6]:
# Standardize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [7]:
for i in range(0, 20):
    #Creating an XGBoost classifier
    model = xgb.XGBClassifier()

    #Training the model on the training data
    model.fit(X_train, y_train)

    #Making predictions on the test set
    y_pred = model.predict(X_test)
    print(y_pred)

[1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1]
[1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1]
[1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1]
[1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1]
[1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1]
[1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1]
[1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1]
[1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1]
[1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1]
[1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1]
[1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1]
[1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1]
[1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1]
[1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1]
[1 1 1 1 1 0 1 0 1 1

In [8]:
df1 = pd.read_csv(DATASET1)
df1.insert(0, "Prediction", y_pred, True)

In [9]:
print(df1)

    Prediction  Round  Seed1             Team1              Team2  Seed2  \
0            1      1      1       Connecticut            Stetson     16   
1            1      1      2           Iowa St    South Dakota St     15   
2            1      1      3          Illinois        Morehead St     14   
3            1      1      4            Auburn               Yale     13   
4            1      1      5      San Diego St                UAB     12   
5            0      1      6               BYU           Duquesne     11   
6            1      1      7     Washington St              Drake     10   
7            0      1      8  Florida Atlantic       Northwestern      9   
8            1      1      1            Purdue         Montata St     16   
9            1      1      2         Tennessee       Saint Peters     15   
10           1      1      3         Creighton              Akron     14   
11           1      1      4            Kansas            Samford     13   
12          

In [9]:
df1.to_csv('2024 R64 prediction.csv', encoding='utf-8', index=False)

### Round of 32

In [10]:
DATASET2 = 'R32 TESTING SET.csv'
df2 = pd.read_csv(DATASET2)
df2.head()

Round  Seed1        Team1          Team2  Seed2  K TEMPO  K TEMPO RANK  \
0      2      1  Connecticut   Northwestern      9   1.6203           -47   
1      2      2      Iowa St  Washington St     10   1.4924           -76   
2      2      3     Illinois       Duquesne     11   3.7182          -205   
3      2      4       Auburn   San Diego St      5   3.9292          -212   
4      2      1       Purdue            TCU      9  -1.6551            82   

   KADJ T  KADJ T RANK   K OFF  ...  BADJT RANK  AVG HGT RANK  EFF HGT RANK  \
0  0.7329          -13  10.548  ...         -18           -80           -82   
1  2.5193         -137  -0.204  ...        -144           100            95   
2  3.5650         -195  14.030  ...        -197          -278           -69   
3  3.8041         -208   8.652  ...        -204           -21           -16   
4 -2.2867          112   9.393  ...         114            -4           -90   

   EXP RANK  TALENT RANK  FT% RANK  OP FT% RANK  PPPO RANK  PPPD RANK  \
0       194          -49        16           13        -45       -164   
1       -28          -32        13         -142         -7        -45   
2      -137         -324      -140           56       -187        100   
3        96            1       -78          205        -99        -25   
4       220            2        49          149        -67         25   

   ELITE SOS RANK  
0             -21  
1             -58  
2             -74  
3              23  
4             -20  

[5 rows x 98 columns]

In [11]:
# Drop player names
df2 = df2.drop(['Team1', 'Team2', 'Round', 'Seed1', 'Seed2'], axis=1)

In [12]:
# Split dataset into X and Y
X_test = df2

In [13]:
# Standardize features
X_test = scaler.fit_transform(X_test)

In [14]:
for i in range(0, 10):
    #Creating an XGBoost classifier
    model = xgb.XGBClassifier()

    #Training the model on the training data
    model.fit(X_train, y_train)

    #Making predictions on the test set
    y_pred = model.predict(X_test)
    print(y_pred)

[1 1 1 1 1 1 1 0 1 1 0 1 0 1 0 1]
[1 1 1 1 1 1 1 0 1 1 0 1 0 1 0 1]
[1 1 1 1 1 1 1 0 1 1 0 1 0 1 0 1]
[1 1 1 1 1 1 1 0 1 1 0 1 0 1 0 1]
[1 1 1 1 1 1 1 0 1 1 0 1 0 1 0 1]
[1 1 1 1 1 1 1 0 1 1 0 1 0 1 0 1]
[1 1 1 1 1 1 1 0 1 1 0 1 0 1 0 1]
[1 1 1 1 1 1 1 0 1 1 0 1 0 1 0 1]
[1 1 1 1 1 1 1 0 1 1 0 1 0 1 0 1]
[1 1 1 1 1 1 1 0 1 1 0 1 0 1 0 1]


In [15]:
df2 = pd.read_csv(DATASET2)
df2.insert(0, "Prediction", y_pred, True)
print(df2)

    Prediction  Round  Seed1           Team1              Team2  Seed2  \
0            1      2      1     Connecticut       Northwestern      9   
1            1      2      2         Iowa St      Washington St     10   
2            1      2      3        Illinois           Duquesne     11   
3            1      2      4          Auburn       San Diego St      5   
4            1      2      1          Purdue                TCU      9   
5            1      2      2       Tennessee              Texas      7   
6            1      2      3       Creighton             Oregon     11   
7            0      2      4          Kansas            Gonzaga      5   
8            1      2      1         Houston          Texas A&M      9   
9            1      2      2       Marquette           Colorado     10   
10           0      2      3        Kentucky  North Carolina St     11   
11           1      2      4            Duke          Wisconsin      5   
12           0      2      1  North Ca

In [29]:
df2.to_csv('2024 R32 prediction.csv', encoding='utf-8', index=False)

### Sweet 16

In [16]:
DATASET3 = 'R16 TESTING SET.csv'
df3 = pd.read_csv(DATASET3)
df3.head()

Round  Seed1        Team1      Team2  Seed2  K TEMPO  K TEMPO RANK  KADJ T  \
0      3      1  Connecticut     Auburn      4  -4.7313           245 -5.3344   
1      3      2      Iowa St   Illinois      3  -2.3785           133 -2.5487   
2      3      1       Purdue    Gonzaga      5  -0.8088            46 -1.7142   
3      3      2    Tennessee  Creighton      3   2.6156          -149  2.1726   
4      3      1      Houston       Duke      4  -3.5721           127 -3.4103   

   KADJ T RANK  K OFF  ...  BADJT RANK  AVG HGT RANK  EFF HGT RANK  EXP RANK  \
0          271  5.344  ...         267           -62           -48       156   
1          123 -8.412  ...         114            94            10       194   
2           92 -0.303  ...          83           -49           -52       -10   
3         -128 -3.820  ...        -135           250           149        17   
4          117 -5.172  ...         132           311           328      -254   

   TALENT RANK  FT% RANK  OP FT% RANK  PPPO RANK  PPPD RANK  ELITE SOS RANK  
0          -34        32          -83        -11         14             -50  
1           25       201          -30         58       -145              -3  
2           39        28          -19          1         25             -78  
3           -6        57         -250         26        -61              -8  
4           19       112          -27         28        -44             -64  

[5 rows x 98 columns]

In [17]:
# Drop player names
df3 = df3.drop(['Team1', 'Team2', 'Round', 'Seed1', 'Seed2'], axis=1)

X_test = df3

X_test = scaler.fit_transform(X_test)

In [18]:
for i in range(0, 10):
    #Creating an XGBoost classifier
    model = xgb.XGBClassifier()

    #Training the model on the training data
    model.fit(X_train, y_train)

    #Making predictions on the test set
    y_pred = model.predict(X_test)
    print(y_pred)

[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]


In [19]:
df3 = pd.read_csv(DATASET3)
df3.insert(0, "Prediction", y_pred, True)
print(df3)

   Prediction  Round  Seed1           Team1              Team2  Seed2  \
0           1      3      1     Connecticut             Auburn      4   
1           1      3      2         Iowa St           Illinois      3   
2           1      3      1          Purdue            Gonzaga      5   
3           1      3      2       Tennessee          Creighton      3   
4           1      3      1         Houston               Duke      4   
5           1      3      2       Marquette  North Carolina St     11   
6           0      3      8  Mississippi St            Alabama      4   
7           1      3      2         Arizona         New Mexico     11   

   K TEMPO  K TEMPO RANK  KADJ T  KADJ T RANK  ...  BADJT RANK  AVG HGT RANK  \
0  -4.7313           245 -5.3344          271  ...         267           -62   
1  -2.3785           133 -2.5487          123  ...         114            94   
2  -0.8088            46 -1.7142           92  ...          83           -49   
3   2.6156          -1

In [37]:
df3.to_csv('2024 R16 prediction.csv', encoding='utf-8', index=False)

### Elite 8

In [20]:
DATASET4 = 'R8 TESTING SET.csv'
df4 = pd.read_csv(DATASET4)
df4.head()

Round  Seed1        Team1      Team2  Seed2  K TEMPO  K TEMPO RANK  KADJ T  \
0      4      1  Connecticut    Iowa St      2  -1.9397           100 -2.8856   
1      4      1       Purdue  Tennessee      2  -1.6050            80 -1.8239   
2      4      1      Houston  Marquette      2  -5.1676           228 -5.7093   
3      4      4      Alabama    Arizona      2   0.7865            -4  0.8082   

   KADJ T RANK   K OFF  ...  BADJT RANK  AVG HGT RANK  EFF HGT RANK  EXP RANK  \
0          150  12.262  ...         155           -78           -91        41   
1           96   6.908  ...          90          -221          -153       122   
2          257   0.613  ...         263           295           313      -127   
3           -7   4.059  ...          -3           -17           -29       -40   

   TALENT RANK  FT% RANK  OP FT% RANK  PPPO RANK  PPPD RANK  ELITE SOS RANK  
0          -28      -190           63        -63         20              -5  
1            7       112          107        -40         58              -6  
2          -17        79         -332         -6        -59               6  
3           99      -185          180         -6        249             -40  

[4 rows x 98 columns]

In [21]:
# Drop player names
df4 = df4.drop(['Team1', 'Team2', 'Round', 'Seed1', 'Seed2'], axis=1)

X_test = df4

X_test = scaler.fit_transform(X_test)

In [22]:
for i in range(0, 10):
    #Creating an XGBoost classifier
    model = xgb.XGBClassifier()

    #Training the model on the training data
    model.fit(X_train, y_train)

    #Making predictions on the test set
    y_pred = model.predict(X_test)
    print(y_pred)

[1 1 1 1]
[1 1 1 1]
[1 1 1 1]
[1 1 1 1]
[1 1 1 1]
[1 1 1 1]
[1 1 1 1]
[1 1 1 1]
[1 1 1 1]
[1 1 1 1]


In [23]:
df4 = pd.read_csv(DATASET4)
df4.insert(0, "Prediction", y_pred, True)
print(df4)

   Prediction  Round  Seed1        Team1      Team2  Seed2  K TEMPO  \
0           1      4      1  Connecticut    Iowa St      2  -1.9397   
1           1      4      1       Purdue  Tennessee      2  -1.6050   
2           1      4      1      Houston  Marquette      2  -5.1676   
3           1      4      4      Alabama    Arizona      2   0.7865   

   K TEMPO RANK  KADJ T  KADJ T RANK  ...  BADJT RANK  AVG HGT RANK  \
0           100 -2.8856          150  ...         155           -78   
1            80 -1.8239           96  ...          90          -221   
2           228 -5.7093          257  ...         263           295   
3            -4  0.8082           -7  ...          -3           -17   

   EFF HGT RANK  EXP RANK  TALENT RANK  FT% RANK  OP FT% RANK  PPPO RANK  \
0           -91        41          -28      -190           63        -63   
1          -153       122            7       112          107        -40   
2           313      -127          -17        79         -33

### Final 4

In [24]:
DATASET5 = 'R4 TESTING SET.csv'
df5 = pd.read_csv(DATASET5)
df5.head()

Round  Seed1        Team1    Team2  Seed2  K TEMPO  K TEMPO RANK  KADJ T  \
0      5      1  Connecticut  Alabama      4  -7.9309           292 -8.1918   
1      5      1       Purdue  Houston      1   4.8272          -207  4.1103   

   KADJ T RANK  K OFF  ...  BADJT RANK  AVG HGT RANK  EFF HGT RANK  EXP RANK  \
0          320  0.996  ...         312            -9            20       127   
1         -173  6.396  ...        -181          -300          -337       128   

   TALENT RANK  FT% RANK  OP FT% RANK  PPPO RANK  PPPD RANK  ELITE SOS RANK  
0          -71        81         -113         -1       -241              12  
1           29      -107          214        -32         66              -3  

[2 rows x 98 columns]

In [25]:
# Drop player names
df5 = df5.drop(['Team1', 'Team2', 'Round', 'Seed1', 'Seed2'], axis=1)

X_test = df5

X_test = scaler.fit_transform(X_test)

In [26]:
for i in range(0, 10):
    #Creating an XGBoost classifier
    model = xgb.XGBClassifier()

    #Training the model on the training data
    model.fit(X_train, y_train)

    #Making predictions on the test set
    y_pred = model.predict(X_test)
    print(y_pred)

[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]


In [27]:
df5 = pd.read_csv(DATASET5)
df5.insert(0, "Prediction", y_pred, True)
print(df5)

   Prediction  Round  Seed1        Team1    Team2  Seed2  K TEMPO  \
0           1      5      1  Connecticut  Alabama      4  -7.9309   
1           0      5      1       Purdue  Houston      1   4.8272   

   K TEMPO RANK  KADJ T  KADJ T RANK  ...  BADJT RANK  AVG HGT RANK  \
0           292 -8.1918          320  ...         312            -9   
1          -207  4.1103         -173  ...        -181          -300   

   EFF HGT RANK  EXP RANK  TALENT RANK  FT% RANK  OP FT% RANK  PPPO RANK  \
0            20       127          -71        81         -113         -1   
1          -337       128           29      -107          214        -32   

   PPPD RANK  ELITE SOS RANK  
0       -241              12  
1         66              -3  

[2 rows x 99 columns]


### FINAL

In [28]:
DATASET7 = 'R2 TESTING SET.csv'
df7 = pd.read_csv(DATASET7)
df7.head()

Round  Seed1        Team1    Team2  Seed2  K TEMPO  K TEMPO RANK  KADJ T  \
0      6      1  Connecticut  Houston      1   2.0728           -52  1.1862   

   KADJ T RANK  K OFF  ...  BADJT RANK  AVG HGT RANK  EFF HGT RANK  EXP RANK  \
0          -19  9.651  ...         -24          -319          -310       186   

   TALENT RANK  FT% RANK  OP FT% RANK  PPPO RANK  PPPD RANK  ELITE SOS RANK  
0           15      -198          196        -35         21               8  

[1 rows x 98 columns]

In [29]:
# Drop player names
df7 = df7.drop(['Team1', 'Team2', 'Round', 'Seed1', 'Seed2'], axis=1)

X_test = df7

X_test = scaler.fit_transform(X_test)

In [30]:
for i in range(0, 10):
    #Creating an XGBoost classifier
    model = xgb.XGBClassifier()

    #Training the model on the training data
    model.fit(X_train, y_train)

    #Making predictions on the test set
    y_pred = model.predict(X_test)
    print(y_pred)

[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]
[1]


### First Four

In [31]:
DATASET6 = 'F4 TESTING SET.csv'
df6 = pd.read_csv(DATASET6)
df6.head()

Round  Seed1        Team1       Team2  Seed2  K TEMPO  K TEMPO RANK  \
0      1     10  Colorado St    Virginia     10   5.2295           -80   
1      1     10     Colorado    Boise St     10   2.4845          -141   
2      1     16    Grambling  Montana St     16  -0.1597            11   
3      1     16       Howard      Wagner     16   6.5981          -230   

   KADJ T  KADJ T RANK   K OFF  ...  BADJT RANK  AVG HGT RANK  EFF HGT RANK  \
0  5.8921          -92  9.3220  ...         -94           200           210   
1  0.7015          -56  2.4400  ...         -75           -15          -142   
2 -1.2871           69  8.5090  ...          48          -188          -205   
3  6.2845         -198  8.9186  ...        -200           -19           -35   

   EXP RANK  TALENT RANK  FT% RANK  OP FT% RANK  PPPO RANK  PPPD RANK  \
0      -279           98      -300          -22       -189        112   
1       -47          -61       -79          -89        -40         13   
2        55         -288       -98          -42       -149       -119   
3      -180         -268      -184           68       -168        200   

   ELITE SOS RANK  
0              -7  
1              10  
2            -232  
3              -8  

[4 rows x 98 columns]

In [32]:
# Drop player names
df6 = df6.drop(['Team1', 'Team2', 'Round', 'Seed1', 'Seed2'], axis=1)

X_test = df6

X_test = scaler.fit_transform(X_test)

print(X_test)

[[ 0.65092094  0.34131703  0.91569168 -0.23854133  0.71816902 -0.83787781
   0.15104058 -0.29520898  0.84254933  0.49762506  0.6162228   0.16101849
  -0.37207704  0.42771846 -0.51870425  0.03783734  0.74312677 -0.6144677
  -1.69245584 -1.23624508  0.45083482 -0.84307293  0.38706402  1.05107513
   0.14097545  0.7656974  -0.51832106 -0.41872166 -0.99392887  0.15014605
  -0.15014605  0.99392887  0.64165429  1.44687227  1.34613411 -1.65338983
   0.79475876 -1.69580059 -0.18124986 -0.72868458  0.66511894 -1.31877278
   1.31877278  0.6282292  -0.6282292   0.88568239 -1.45432487 -1.60691341
   1.32399774 -1.69077512  1.72786106 -0.41284265  0.73532569  0.825137
  -0.37903261 -0.56502359  0.55286881 -0.2590567   0.20921604  0.6444503
  -0.729504    0.75350529 -0.10178271  0.77668893 -1.02988168  0.19618342
   0.97122494 -0.24495991 -0.24495991  0.97122494  0.36439122 -1.58974645
   1.29519941  1.47704194  0.91624821  1.68359021 -0.29522634  1.0039414
   0.33803877  1.32739456 -1.32509645  0.71

In [33]:
for i in range(0, 10):
    #Creating an XGBoost classifier
    model = xgb.XGBClassifier()

    #Training the model on the training data
    model.fit(X_train, y_train)

    #Making predictions on the test set
    y_pred = model.predict(X_test)
    print(y_pred)

[1 1 1 0]
[1 1 1 0]
[1 1 1 0]
[1 1 1 0]
[1 1 1 0]
[1 1 1 0]
[1 1 1 0]
[1 1 1 0]
[1 1 1 0]
[1 1 1 0]


In [34]:
df6 = pd.read_csv(DATASET6)
df6.insert(0, "Prediction", y_pred, True)
print(df6)

   Prediction  Round  Seed1        Team1       Team2  Seed2  K TEMPO  \
0           1      1     10  Colorado St    Virginia     10   5.2295   
1           1      1     10     Colorado    Boise St     10   2.4845   
2           1      1     16    Grambling  Montana St     16  -0.1597   
3           0      1     16       Howard      Wagner     16   6.5981   

   K TEMPO RANK  KADJ T  KADJ T RANK  ...  BADJT RANK  AVG HGT RANK  \
0           -80  5.8921          -92  ...         -94           200   
1          -141  0.7015          -56  ...         -75           -15   
2            11 -1.2871           69  ...          48          -188   
3          -230  6.2845         -198  ...        -200           -19   

   EFF HGT RANK  EXP RANK  TALENT RANK  FT% RANK  OP FT% RANK  PPPO RANK  \
0           210      -279           98      -300          -22       -189   
1          -142       -47          -61       -79          -89        -40   
2          -205        55         -288       -98       