In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
import pprint
from sklearn.preprocessing import StandardScaler
%matplotlib inline

from sklearn.metrics import f1_score, recall_score, accuracy_score, precision_score, confusion_matrix
from sklearn.metrics import r2_score, roc_auc_score, roc_curve, classification_report
import xgboost as xgb
from sklearn.model_selection import cross_validate
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import KFold

FULL_DATASET = 'FULL TRAINING SET updated.csv'

### Round of 64

In [2]:
DATASET1 = 'R64 TESTING SET.csv'
df = pd.read_csv(FULL_DATASET)
df1 = pd.read_csv(DATASET1)

print(df.head())
print(df1.head())

   Round  Seed1           Team1           Team2  Seed2  Result  K TEMPO  \
0      1      1  North Carolina  Mount St Marys     16       1   7.6847   
1      1      2       Tennessee        American     15       1  11.7930   
2      1      3      Louisville        Boise St     14       1  -5.4011   
3      1      4   Washington St        Winthrop     13       1  -4.4331   
4      1      5      Notre Dame    George Mason     12       1   8.4834   

   K TEMPO RANK  KADJ T  KADJ T RANK  ...  BADJT RANK  AVG HGT RANK  \
0          -120  6.6882         -134  ...        -150          -195   
1          -309  9.9867         -301  ...        -300          -167   
2           151 -5.5255          142  ...         141           -67   
3            44 -3.1859           38  ...          33          -200   
4          -260  7.9935         -263  ...        -250          -148   

   EFF HGT RANK  EXP RANK  TALENT RANK  FT% RANK  OP FT% RANK  PPPO RANK  \
0           -91       -49         -197      -1

In [3]:
df.isnull().sum()

Round             0
Seed1             0
Team1             0
Team2             0
Seed2             0
                 ..
FT% RANK          0
OP FT% RANK       0
PPPO RANK         0
PPPD RANK         0
ELITE SOS RANK    0
Length: 99, dtype: int64

In [4]:
# Drop player names
df = df.drop(['Team1', 'Team2'], axis=1)
df1 = df1.drop(['Team1', 'Team2'], axis=1)

In [5]:
# Split dataset into X and Y
X_train = df.iloc[:, df.columns != 'Result']
y_train = df['Result']
X_test = df1

In [6]:
for i in range(0, 20):
    #Creating an XGBoost classifier
    model = xgb.XGBClassifier()

    #Training the model on the training data
    model.fit(X_train, y_train)

    #Making predictions on the test set
    y_pred = model.predict(X_test)
    print(y_pred)

[1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 0 1]
[1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 0 1]
[1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 0 1]
[1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 0 1]
[1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 0 1]
[1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 0 1]
[1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 0 1]
[1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 0 1]
[1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 0 1]
[1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 0 1]
[1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 0 1]
[1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 0 1]
[1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 0 1]
[1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 0 1]
[1 1 1 1 1 0 0 0 1 1

In [7]:
df1 = pd.read_csv(DATASET1)
df1.insert(0, "Prediction", y_pred, True)

In [8]:
print(df1)

    Prediction  Round  Seed1             Team1              Team2  Seed2  \
0            1      1      1       Connecticut            Stetson     16   
1            1      1      2           Iowa St    South Dakota St     15   
2            1      1      3          Illinois        Morehead St     14   
3            1      1      4            Auburn               Yale     13   
4            1      1      5      San Diego St                UAB     12   
5            0      1      6               BYU           Duquesne     11   
6            0      1      7     Washington St              Drake     10   
7            0      1      8  Florida Atlantic       Northwestern      9   
8            1      1      1            Purdue         Montata St     16   
9            1      1      2         Tennessee       Saint Peters     15   
10           1      1      3         Creighton              Akron     14   
11           0      1      4            Kansas            Samford     13   
12          

In [9]:
df1.to_csv('2024 R64 prediction.csv', encoding='utf-8', index=False)

### Round of 32

In [23]:
DATASET2 = 'R32 TESTING SET.csv'
df2 = pd.read_csv(DATASET2)
df2.head()

Round  Seed1        Team1         Team2  Seed2  K TEMPO  K TEMPO RANK  \
0      2      1  Connecticut  Northwestern      9   1.6203           -47   
1      2      2      Iowa St         Drake     10  -0.5008            39   
2      2      3     Illinois      Duquesne     11   3.7182          -205   
3      2      4       Auburn  San Diego St      5   3.9292          -212   
4      2      1       Purdue           TCU      9  -1.6551            82   

   KADJ T  KADJ T RANK   K OFF  ...  BADJT RANK  AVG HGT RANK  EFF HGT RANK  \
0  0.7329          -13  10.548  ...         -18           -80           -82   
1 -0.4985           29  -3.791  ...          16          -204           -65   
2  3.5650         -195  14.030  ...        -197          -278           -69   
3  3.8041         -208   8.652  ...        -204           -21           -16   
4 -2.2867          112   9.393  ...         114            -4           -90   

   EXP RANK  TALENT RANK  FT% RANK  OP FT% RANK  PPPO RANK  PPPD RANK  \
0       194          -49        16           13        -45       -164   
1       -15          -87       245           54         37        -60   
2      -137         -324      -140           56       -187        100   
3        96            1       -78          205        -99        -25   
4       220            2        49          149        -67         25   

   ELITE SOS RANK  
0             -21  
1            -116  
2             -74  
3              23  
4             -20  

[5 rows x 98 columns]

In [24]:
# Drop player names
df2 = df2.drop(['Team1', 'Team2'], axis=1)

In [25]:
# Split dataset into X and Y
X_test = df2

In [27]:
for i in range(0, 30):
    #Creating an XGBoost classifier
    model = xgb.XGBClassifier()

    #Training the model on the training data
    model.fit(X_train, y_train)

    #Making predictions on the test set
    y_pred = model.predict(X_test)
    print(y_pred)

[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1]
[1 1 1 1 1 1 1

In [28]:
df2 = pd.read_csv(DATASET2)
df2.insert(0, "Prediction", y_pred, True)

In [29]:
df2.to_csv('2024 R32 prediction.csv', encoding='utf-8', index=False)

### Sweet 16

In [30]:
DATASET3 = 'R16 TESTING SET.csv'
df3 = pd.read_csv(DATASET3)
df3.head()

Round  Seed1        Team1      Team2  Seed2  K TEMPO  K TEMPO RANK  KADJ T  \
0      3      1  Connecticut     Auburn      4  -4.7313           245 -5.3344   
1      3      2      Iowa St   Illinois      3  -2.3785           133 -2.5487   
2      3      1       Purdue    Gonzaga      5  -0.8088            46 -1.7142   
3      3      2    Tennessee  Creighton      3   2.6156          -149  2.1726   
4      3      1      Houston  Wisconsin      5  -1.6109            35 -1.8857   

   KADJ T RANK  K OFF  ...  BADJT RANK  AVG HGT RANK  EFF HGT RANK  EXP RANK  \
0          271  5.344  ...         267           -62           -48       156   
1          123 -8.412  ...         114            94            10       194   
2           92 -0.303  ...          83           -49           -52       -10   
3         -128 -3.820  ...        -135           250           149        17   
4           41 -0.085  ...          37           323           326       -95   

   TALENT RANK  FT% RANK  OP FT% RANK  PPPO RANK  PPPD RANK  ELITE SOS RANK  
0          -34        32          -83        -11         14             -50  
1           25       201          -30         58       -145              -3  
2           39        28          -19          1         25             -78  
3           -6        57         -250         26        -61              -8  
4          -30       249         -221         -2       -187               7  

[5 rows x 98 columns]

In [33]:
# Drop player names
df3 = df3.drop(['Team1', 'Team2'], axis=1)

X_test = df3

In [34]:
for i in range(0, 30):
    #Creating an XGBoost classifier
    model = xgb.XGBClassifier()

    #Training the model on the training data
    model.fit(X_train, y_train)

    #Making predictions on the test set
    y_pred = model.predict(X_test)
    print(y_pred)

[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]
[1 1 1 1 1 1 0 1]


In [35]:
df3 = pd.read_csv(DATASET3)
df3.insert(0, "Prediction", y_pred, True)

In [37]:
df3.to_csv('2024 R16 prediction.csv', encoding='utf-8', index=False)

### Elite 8

In [38]:
DATASET4 = 'R8 TESTING SET.csv'
df4 = pd.read_csv(DATASET4)
df4.head()

Round  Seed1        Team1      Team2  Seed2  K TEMPO  K TEMPO RANK  KADJ T  \
0      4      1  Connecticut    Iowa St      2  -1.9397           100 -2.8856   
1      4      1       Purdue  Tennessee      2  -1.6050            80 -1.8239   
2      4      1      Houston  Marquette      2  -5.1676           228 -5.7093   
3      4      4      Alabama    Arizona      2   0.7865            -4  0.8082   

   KADJ T RANK   K OFF  ...  BADJT RANK  AVG HGT RANK  EFF HGT RANK  EXP RANK  \
0          150  12.262  ...         155           -78           -91        41   
1           96   6.908  ...          90          -221          -153       122   
2          257   0.613  ...         263           295           313      -127   
3           -7   4.059  ...          -3           -17           -29       -40   

   TALENT RANK  FT% RANK  OP FT% RANK  PPPO RANK  PPPD RANK  ELITE SOS RANK  
0          -28      -190           63        -63         20              -5  
1            7       112          107        -40         58              -6  
2          -17        79         -332         -6        -59               6  
3           99      -185          180         -6        249             -40  

[4 rows x 98 columns]

In [39]:
# Drop player names
df4 = df4.drop(['Team1', 'Team2'], axis=1)

X_test = df4

In [40]:
for i in range(0, 30):
    #Creating an XGBoost classifier
    model = xgb.XGBClassifier()

    #Training the model on the training data
    model.fit(X_train, y_train)

    #Making predictions on the test set
    y_pred = model.predict(X_test)
    print(y_pred)

[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]
[1 0 1 1]


In [42]:
df4 = pd.read_csv(DATASET4)
df4.insert(0, "Prediction", y_pred, True)
df4.to_csv('2024 R8 prediction.csv', encoding='utf-8', index=False)

### Final 4

In [44]:
DATASET5 = 'R4 TESTING SET.csv'
df5 = pd.read_csv(DATASET5)
df5.head()

Round  Seed1        Team1      Team2  Seed2  K TEMPO  K TEMPO RANK  KADJ T  \
0      5      1  Connecticut    Alabama      4  -7.9309           292 -8.1918   
1      5      1      Houston  Tennessee      2  -6.4322           287 -5.9342   
2      6      1  Connecticut    Houston      1   2.0728           -52  1.1862   

   KADJ T RANK  K OFF  ...  BADJT RANK  AVG HGT RANK  EFF HGT RANK  EXP RANK  \
0          320  0.996  ...         312            -9            20       127   
1          269  0.512  ...         271            79           184        -6   
2          -19  9.651  ...         -24          -319          -310       186   

   TALENT RANK  FT% RANK  OP FT% RANK  PPPO RANK  PPPD RANK  ELITE SOS RANK  
0          -71        81         -113         -1       -241              12  
1          -22       219         -107         -8         -8              -3  
2           15      -198          196        -35         21               8  

[3 rows x 98 columns]

In [45]:
# Drop player names
df5 = df5.drop(['Team1', 'Team2'], axis=1)

X_test = df5

In [46]:
for i in range(0, 30):
    #Creating an XGBoost classifier
    model = xgb.XGBClassifier()

    #Training the model on the training data
    model.fit(X_train, y_train)

    #Making predictions on the test set
    y_pred = model.predict(X_test)
    print(y_pred)

[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 0]


In [47]:
df5 = pd.read_csv(DATASET5)
df5.insert(0, "Prediction", y_pred, True)
df5.to_csv('2024 R4 prediction.csv', encoding='utf-8', index=False)

### First Four

In [6]:
DATASET6 = 'F4 TESTING SET.csv'
df6 = pd.read_csv(DATASET6)
df6.head()

Round  Seed1        Team1       Team2  Seed2  K TEMPO  K TEMPO RANK  \
0      1     10  Colorado St    Virginia     10   5.2295           -80   
1      1     10     Colorado    Boise St     10   2.4845          -141   
2      1     16    Grambling  Montana St     16  -0.1597            11   
3      1     16       Howard      Wagner     16   6.5981          -230   

   KADJ T  KADJ T RANK   K OFF  ...  BADJT RANK  AVG HGT RANK  EFF HGT RANK  \
0  5.8921          -92  9.3220  ...         -94           200           210   
1  0.7015          -56  2.4400  ...         -75           -15          -142   
2 -1.2871           69  8.5090  ...          48          -188          -205   
3  6.2845         -198  8.9186  ...        -200           -19           -35   

   EXP RANK  TALENT RANK  FT% RANK  OP FT% RANK  PPPO RANK  PPPD RANK  \
0      -279           98      -300          -22       -189        112   
1       -47          -61       -79          -89        -40         13   
2        55         -288       -98          -42       -149       -119   
3      -180         -268      -184           68       -168        200   

   ELITE SOS RANK  
0              -7  
1              10  
2            -232  
3              -8  

[4 rows x 98 columns]

In [7]:
# Drop player names
df6 = df6.drop(['Team1', 'Team2'], axis=1)

X_test = df6

In [8]:
for i in range(0, 30):
    #Creating an XGBoost classifier
    model = xgb.XGBClassifier()

    #Training the model on the training data
    model.fit(X_train, y_train)

    #Making predictions on the test set
    y_pred = model.predict(X_test)
    print(y_pred)

[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
[0 0 1 1]
